### ISSUE TITLE
wildcard subdomain detected, skipping brute force

### ISSUE THREAD

**Issue by uprootnetworks** [b3n-j4m1n/snrublist3r#1]
Was running into issues with pycares on Ubuntu18.04, so decided to give it a shot on a fresh environment running 22.04.  That resolved the python issues I was running into.  However, now I am getting a message saying `"wildcard subdomain detected, skipping brute force".`

This ultimately results in 0 subdomains found 

`uproot@uprootims:~/snrublist3r$ python3.10 snrublist3r.py -d example.com -b -m --disable-scraping 

                ⠀⠀⡠⠐⠀⠈⠁⠐⠪⢟⢁⡰⢄⠀⠀⠀⠀⠀⠀
                ⢠⠺⠀⠀⠀⠀⠀⠠⠆⡀⢣⢀⡀⢡⠀⠀⠀⠀⠀
                ⡆⡇⠀⠀⠀⠀⠀⠰⠀⡡⢳⣄⡈⡾⠀⠀⠀⠀⠀
                ⠰⡡⡀⠀⠀⠀⢀⡠⠀⢇⠻⣺⡝⠁⠀⠀⠀⠀⠀
                ⠀⢭⡩⠃⠯⣉⠡⠃⠀⠈⠊⡙⠀⠀⠀⠀⠀⠀⠀
                ⢀⠜⠤⡄⠀⠀⠀⠀⢀⣤⠌⢣⡀⣀⠀⠀⠀⠀⠀
                ⣎⡠⢺⣁⣀⣠⡴⣾⡛⠁⠀⠀⠹⢣⠹⡢⡀⠀⠀
                ⠈⠀⠀⠀⠀⠀⠀⠀⢨⢶⢤⢀⠔⢸⡇⢣⠱⡀⠀
                ⠀⠀⠀⠀⠀⠀⠀⠀⣼⢼⠾⣴⠧⡚⢴⠋⠀⠱⠀
                ⠀⠀⠀⠀⠀⠀⠀⢀⢿⡀⣇⠹⢀⠛⣸⢡⠀⠀⡇
                ⠀⠀⠀⠀⡨⢷⡺⠷⣬⢱⢻⠀⠏⡰⠃⢸⠀⠀⠀
                ⠀⠀⠀⢘⠤⢭⡿⡻⠆⠈⣷⣾⣔⣁⣀⡼⠀⠀⡄
                ⠀⠀⠀⠈⠢⡁⢸⢩⣷⣀⡸⠀⡇⠀⠀⠀⠀⣠⡇
snrublist3r            ⠉⠉⠁⠘⠛⠛⠛⠛⠚⠛⠛⠒⠃      
    
[!] WARNING, -nf/--nameservers-file not set, using system settings (potential DoS)
[*] snrubing starting for example.com
[!] scraping disabled
[*] starting raw brute force...
**[-] wildcard subdomain detected, skipping brute force**
[*] mutating known subdomains
[*] 0 subdomain mutations generated
[?] continue with mutation brute force (y/n)? n^Hy
[-] invalid response

[*] DNS Brute Force: 0
FINISHED! 0 unique subdomains snrubed in 6.47 seconds
uproot@uprootims:~/snrublist3r$ `

**Comment by b3n-j4m1n** [comment]
It works fine for me.
![image](https://github.com/b3n-j4m1n/snrublist3r/assets/19149345/88823cd8-61a3-4099-adc0-90fe7850d0c2)

The brute force does a random nonexistent domain first, to prevent 100,000 false positives.

```
    def run(self, domain, subdomains):
        letters = string.ascii_lowercase
        random_sub = ''.join(random.choice(letters) for _ in range(10))
        try:
            socket.gethostbyname(random_sub + "." + domain)
            logging.error(f"{Fore.LIGHTRED_EX}[-] wildcard subdomain detected, skipping brute force")
            return self.results.data
```

**Comment by uprootnetworks** [comment]
Looks like issue was due to having a search domain configured under netplan.  If I remove the search domain, it works fine

Otherwise, the system was appending the random sub with my search domain and it was resolving to the same IP regardless of what was searched



From: b3n-j4m1n ***@***.***>
Date: Monday, October 30, 2023 at 5:21 PM
To: b3n-j4m1n/snrublist3r ***@***.***>
Cc: Ryan Ashcraft ***@***.***>, Author ***@***.***>
Subject: Re: [b3n-j4m1n/snrublist3r] wildcard subdomain detected, skipping brute force (Issue #1)

It works fine for me.
[image]<https://user-images.githubusercontent.com/19149345/279216808-88823cd8-61a3-4099-adc0-90fe7850d0c2.png>

The brute force does a random nonexistent domain first, to prevent 100,000 false positives.

    def run(self, domain, subdomains):

        letters = string.ascii_lowercase

        random_sub = ''.join(random.choice(letters) for _ in range(10))

        try:

            socket.gethostbyname(random_sub + "." + domain)

            logging.error(f"{Fore.LIGHTRED_EX}[-] wildcard subdomain detected, skipping brute force")

            return self.results.data
